openapi: 3.0.3
info:
  title: WeDoComputers dotnet API - OpenAPI 3.0
  description: This is a sample API based on the OpenAPI 3.0 specification.
  termsOfService: http://swagger.io/terms/
  contact:
    email: jby@netic.dk
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
tags:
  - name: Computer
    description: Everything about computers
    externalDocs:
      description: Find out more
      url: http://swagger.io
  - name: user
    description: Operations about user
paths:
  /computer/{computerId}:
    $ref: './computers.yaml#/paths/~1computer'
#  /computer/findByStatus:
#    $ref: './computers.yaml#/paths/~1computer/~1findByStatus'

#  /computer/findByTags:
#    $ref: './computers.yaml#/paths/~1computer/~1findByTags'
